/* Generated by Yosys 0.47+149 (git sha1 889894a6d, clang++ 18.1.8 -fPIC -O3) */

module \controller.aiger (response, request);
  input request;
  wire request;
  output response;
  wire response;
  assign response = request;
endmodule
