/* Generated by Yosys 0.47+149 (git sha1 889894a6d, clang++ 18.1.8 -fPIC -O3) */

module \controller.aiger (ant_1, ant_2, cons, p, q, r, ant);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input ant;
  wire ant;
  input ant_1;
  wire ant_1;
  input ant_2;
  wire ant_2;
  output cons;
  wire cons;
  output p;
  wire p;
  output q;
  wire q;
  output r;
  wire r;
  assign _00_ = _04_ & _06_;
  assign _02_ = ant_1 & ant_2;
  assign _03_ = ant & _02_;
  assign _05_ = _01_ & _02_;
  assign _01_ = ~ant;
  assign p = ~_00_;
  assign _04_ = ~_03_;
  assign _06_ = ~_05_;
  assign q = 1'h0;
  assign cons = ant;
  assign r = p;
endmodule
